apiVersion: apps/v1
kind: Deployment
metadata:
  name: chapter-argocd
  namespace: chapter-argocd
spec:
  selector:
    matchLabels:
      app: chapter-pod-argocd
  template:
    metadata:
      labels:
        app: chapter-pod-argocd
    spec:
      containers:
        - name: chapter-container-argocd
          image: paulomendesdigital/green-pod
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: chapter-argocd-svc
  namespace: chapter-argocd
spec:
  selector:
    app: chapter-pod-argocd
  ports:
    - port: 80
      targetPort: 80
