apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: chapter-argocd
  newName: paulomendesdigital/chapter-argocd
  newTag: 2a2cfec9f3ddf878087c71a4666e29ca7d1dedaf
