apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: chapter-argocd
  newName: paulomendesdigital/chapter-argocd
  newTag: aabb436fe5f620b7cee8b269c17a1674dcc56d26
